### ISSUE TITLE
Create a .py complete example configuration file for *Rocksanne I-X*

### ISSUE THREAD

**Issue by rubendibattista** [skyward-er/skyward-salome-rocket-mesher#2]

**Comment by massimiliano-leoni** [comment]
The current mesher.py already has specifications from Roxanne I-X.
Do you just want a separate file?

**Comment by rubendibattista** [comment]
@massimiliano-leoni the geometry dimensions are all correct? 

Anyway I'm writing this waiting for the others to join the org here on Github so they can become proficient with this piece of software writing example configuration files

**Comment by massimiliano-leoni** [comment]
@rubendibattista they are correct, according to what I was told from federico rovere & others. I can change them if they are not. We should check the script.

Anyway, I will create a separate file now.

**Comment by rubendibattista** [comment]
@massimiliano-leoni ok.

**Comment by massimiliano-leoni** [comment]
@rubendibattista b028490 could be what you want?

**Comment by rubendibattista** [comment]
@massimiliano-leoni ok. In the next days we're going to do a last check on dimension and then we close this issue.

**Comment by massimiliano-leoni** [comment]
I was wrong, I must have played with the shapes for testing purposes, so we need to set them again in meshes/r1x.py
