### ISSUE TITLE
Incompatibiltiy with Salome 9.4.0

### ISSUE THREAD

**Issue by loic-fejoz** [skyward-er/skyward-salome-rocket-mesher#7]
I tried to run the script with Salome 9.4.0 on Debian with:
```
~/download/SALOME-9.4.0-DB10-SRC/salome -t rocketMesher.py
```

Unfortunately, a first error happens because of python3 I guess. I first need to comment out all (sub)imports from `parts/__init__.py`

Then I get following warning:
```
Warning: 'study' argument is no more needed in geomBuilder.New(). Consider updating your script!!!
```

But the one that I don't know what to do with (I do not know Salome):
```
raceback (most recent call last):
  File "/home/loic/projets/skyward-salome-rocket-mesher/rocketMesher.py", line 42, in <module>
    body.buildBody()
  File "/home/loic/projets/skyward-salome-rocket-mesher/parts/Body.py", line 37, in buildBody
    self.body = geompy.MakeSolid([self.body])
  File "/home/loic/Téléchargements/SALOME-9.4.0-DB10-SRC/BINARIES-DB10/GEOM/lib/python3.6/site-packages/salome/salome/geom/geomBuilder.py", line 364, in OpenCallClose
    res = theFunction(self, *args, **kwargs)
  File "/home/loic/Téléchargements/SALOME-9.4.0-DB10-SRC/BINARIES-DB10/GEOM/lib/python3.6/site-packages/salome/salome/geom/geomBuilder.py", line 4974, in MakeSolid
    raise RuntimeError("MakeSolidShells : Unable to create solid from unclosed shape")
RuntimeError: MakeSolidShells : Unable to create solid from unclosed shape
ERROR:salomeContext:SystemExit 1 in method _runAppli.
```

NB: Not sure you need to resolve this. It was just a try after our discussion.

**Comment by rubendibattista** [comment]
Ehi @loic-fejoz thanks for trying this. It was done long time ago, so probably the SALOME API changed. 

I'll ping @massimiliano-leoni to see if we can help us to get this running again.

**Comment by rubendibattista** [comment]
This s probably related: https://docs.salome-platform.org/7/gui/SMESH/smesh_migration_page.html

**Comment by massimiliano-leoni** [comment]
The imports in `__init__.py` can be fixed adding `from parts`.
I can reproduce the other error, although it looks like a regression to me as it worked on older versions of Salome. See https://www.salome-platform.org/forum/forum_10/179945569

**Comment by massimiliano-leoni** [comment]
I pushed a branch that closes this issue. Please confirm the fix and merge.
